using WorkTrace.Application.Abstractions;
using WorkTrace.Application.Abstractions.Repositories;
using WorkTrace.Application.Commands;
using WorkTrace.Application.Results;
using WorkTrace.Application.Validation;
using WorkTrace.Domain.Shared;
using WorkTrace.Domain.WorkItems;

namespace WorkTrace.Application.Handlers;

public sealed class CreateWorkItemHandler : ICommandHandler<CreateWorkItemCommand, CommandResult<WorkItemId>>
{
    private readonly IWorkItemRepository _workItems;
    private readonly IClock _clock;
    private readonly IUnitOfWork _unitOfWork;
    private readonly ICommandValidator<CreateWorkItemCommand> _validator;

    public CreateWorkItemHandler(
        IWorkItemRepository workItems,
        IClock clock,
        IUnitOfWork unitOfWork,
        ICommandValidator<CreateWorkItemCommand> validator)
    {
        _workItems = workItems;
        _clock = clock;
        _unitOfWork = unitOfWork;
        _validator = validator;
    }

    public async Task<CommandResult<WorkItemId>> HandleAsync(CreateWorkItemCommand command, CancellationToken cancellationToken = default)
    {
        var errors = _validator.Validate(command);
        if (errors.Count > 0)
        {
            return CommandResult<WorkItemId>.Failure(errors.ToArray());
        }

        var item = WorkItem.Create(command.Title, command.Kind, command.Description, command.ProjectId, _clock.UtcNow);
        await _workItems.AddAsync(item, cancellationToken);
        await _unitOfWork.SaveChangesAsync(cancellationToken);

        var warnings = new List<CommandWarning>();
        if (string.IsNullOrWhiteSpace(command.Title))
        {
            warnings.Add(new CommandWarning(AppWarningCodes.AutoGeneratedWorkItemTitle, "The work item title was auto-generated.", nameof(command.Title)));
        }

        return CommandResult<WorkItemId>.Success(item.Id, warnings.ToArray());
    }
}

public sealed class UpdateWorkItemHandler : ICommandHandler<UpdateWorkItemCommand, CommandResult>
{
    private readonly IWorkItemRepository _workItems;
    private readonly IUnitOfWork _unitOfWork;
    private readonly IClock _clock;
    private readonly ICommandValidator<UpdateWorkItemCommand> _validator;

    public UpdateWorkItemHandler(
        IWorkItemRepository workItems,
        IUnitOfWork unitOfWork,
        IClock clock,
        ICommandValidator<UpdateWorkItemCommand> validator)
    {
        _workItems = workItems;
        _unitOfWork = unitOfWork;
        _clock = clock;
        _validator = validator;
    }

    public async Task<CommandResult> HandleAsync(UpdateWorkItemCommand command, CancellationToken cancellationToken = default)
    {
        var errors = _validator.Validate(command);
        if (errors.Count > 0)
        {
            return CommandResult.Failure(errors.ToArray());
        }

        var workItem = await _workItems.GetByIdAsync(command.Id, cancellationToken);
        if (workItem is null)
        {
            return CommandResult.Failure(new CommandError(AppErrorCodes.WorkItemNotFound, "The work item could not be found.", nameof(command.Id)));
        }

        var warnings = new List<CommandWarning>();
        var wasArchived = workItem.IsArchived;

        workItem.UpdateDetails(command.Title, command.Kind, command.Description, command.ProjectId, command.Status, _clock.UtcNow);

        if (wasArchived)
        {
            workItem.Restore(_clock.UtcNow);
            warnings.Add(new CommandWarning(AppWarningCodes.RestoredArchivedWorkItem, "The archived work item was restored while updating it.", nameof(command.Id)));
        }

        await _workItems.UpdateAsync(workItem, cancellationToken);
        await _unitOfWork.SaveChangesAsync(cancellationToken);

        return CommandResult.Success(warnings.ToArray());
    }
}

public sealed class ArchiveWorkItemHandler : ICommandHandler<ArchiveWorkItemCommand, CommandResult>
{
    private readonly IWorkItemRepository _workItems;
    private readonly IUnitOfWork _unitOfWork;
    private readonly IClock _clock;
    private readonly ICommandValidator<ArchiveWorkItemCommand> _validator;

    public ArchiveWorkItemHandler(
        IWorkItemRepository workItems,
        IUnitOfWork unitOfWork,
        IClock clock,
        ICommandValidator<ArchiveWorkItemCommand> validator)
    {
        _workItems = workItems;
        _unitOfWork = unitOfWork;
        _clock = clock;
        _validator = validator;
    }

    public async Task<CommandResult> HandleAsync(ArchiveWorkItemCommand command, CancellationToken cancellationToken = default)
    {
        var errors = _validator.Validate(command);
        if (errors.Count > 0)
        {
            return CommandResult.Failure(errors.ToArray());
        }

        var workItem = await _workItems.GetByIdAsync(command.Id, cancellationToken);
        if (workItem is null)
        {
            return CommandResult.Failure(new CommandError(AppErrorCodes.WorkItemNotFound, "The work item could not be found.", nameof(command.Id)));
        }

        workItem.Archive(_clock.UtcNow);
        await _workItems.UpdateAsync(workItem, cancellationToken);
        await _unitOfWork.SaveChangesAsync(cancellationToken);

        return CommandResult.Success();
    }
}

public sealed class RestoreWorkItemHandler : ICommandHandler<RestoreWorkItemCommand, CommandResult>
{
    private readonly IWorkItemRepository _workItems;
    private readonly IUnitOfWork _unitOfWork;
    private readonly IClock _clock;
    private readonly ICommandValidator<RestoreWorkItemCommand> _validator;

    public RestoreWorkItemHandler(
        IWorkItemRepository workItems,
        IUnitOfWork unitOfWork,
        IClock clock,
        ICommandValidator<RestoreWorkItemCommand> validator)
    {
        _workItems = workItems;
        _unitOfWork = unitOfWork;
        _clock = clock;
        _validator = validator;
    }

    public async Task<CommandResult> HandleAsync(RestoreWorkItemCommand command, CancellationToken cancellationToken = default)
    {
        var errors = _validator.Validate(command);
        if (errors.Count > 0)
        {
            return CommandResult.Failure(errors.ToArray());
        }

        var workItem = await _workItems.GetByIdAsync(command.Id, cancellationToken);
        if (workItem is null)
        {
            return CommandResult.Failure(new CommandError(AppErrorCodes.WorkItemNotFound, "The work item could not be found.", nameof(command.Id)));
        }

        workItem.Restore(_clock.UtcNow);
        await _workItems.UpdateAsync(workItem, cancellationToken);
        await _unitOfWork.SaveChangesAsync(cancellationToken);

        return CommandResult.Success();
    }
}
