using WorkTrace.Application.Commands;
using WorkTrace.Application.Handlers;
using WorkTrace.Application.Results;
using WorkTrace.Application.Validation;
using WorkTrace.Domain.WorkItems;

namespace WorkTrace.Application.Tests;

public class WorkItemHandlerTests
{
    [Fact]
    public async Task CreateWorkItem_AutoGeneratesTitle_AndReturnsWarning()
    {
        var repo = new InMemoryWorkItemRepository();
        var clock = new FakeClock { UtcNow = new DateTimeOffset(2026, 03, 28, 12, 0, 0, TimeSpan.Zero) };
        var unitOfWork = new FakeUnitOfWork();
        var handler = new CreateWorkItemHandler(repo, clock, unitOfWork, new CreateWorkItemValidator());

        var result = await handler.HandleAsync(new CreateWorkItemCommand(" "));

        Assert.True(result.IsSuccess);
        Assert.Single(result.Warnings);
        Assert.Equal(AppWarningCodes.AutoGeneratedWorkItemTitle, result.Warnings[0].Code);
        Assert.Equal(1, unitOfWork.SaveChangesCalls);
        Assert.NotNull(await repo.GetByIdAsync(result.Value));
    }

    [Fact]
    public async Task UpdateWorkItem_RestoresArchivedItem()
    {
        var repo = new InMemoryWorkItemRepository();
        var clock = new FakeClock { UtcNow = new DateTimeOffset(2026, 03, 28, 12, 30, 0, TimeSpan.Zero) };
        var unitOfWork = new FakeUnitOfWork();
        var workItem = WorkItem.Create("Build", createdAt: clock.UtcNow.AddMinutes(-15));
        workItem.Archive(clock.UtcNow.AddMinutes(-10));
        await repo.AddAsync(workItem);

        var handler = new UpdateWorkItemHandler(repo, unitOfWork, clock, new UpdateWorkItemValidator());
        var result = await handler.HandleAsync(new UpdateWorkItemCommand(workItem.Id, "Build v2", WorkItemKind.Bug, null, null, WorkItemStatus.InProgress));

        Assert.True(result.IsSuccess);
        Assert.False((await repo.GetByIdAsync(workItem.Id))!.IsArchived);
        Assert.Single(result.Warnings);
        Assert.Equal(AppWarningCodes.RestoredArchivedWorkItem, result.Warnings[0].Code);
    }

    [Fact]
    public async Task ArchiveWorkItem_StopsAtRepositoryLayer()
    {
        var repo = new InMemoryWorkItemRepository();
        var clock = new FakeClock { UtcNow = new DateTimeOffset(2026, 03, 28, 12, 0, 0, TimeSpan.Zero) };
        var unitOfWork = new FakeUnitOfWork();
        var workItem = WorkItem.Create("Build", createdAt: clock.UtcNow.AddMinutes(-5));
        await repo.AddAsync(workItem);

        var handler = new ArchiveWorkItemHandler(repo, unitOfWork, clock, new ArchiveWorkItemValidator());
        var result = await handler.HandleAsync(new ArchiveWorkItemCommand(workItem.Id));

        Assert.True(result.IsSuccess);
        Assert.True((await repo.GetByIdAsync(workItem.Id))!.IsArchived);
    }
}
